### ISSUE TITLE
Certain Sprites not being loaded, instead shows PokeBall

### ISSUE THREAD

**Issue by lankyboy01** [EnvyWare/EnvyCrates#2]
Using the exact same NBT format as the other pokemon that have their sprites showing.

        "nbt": {
            "ndex": {
                "type": "short",
                "data": 893,
                "subData": {}
            },
            "gender": {
                "type": "byte",
                "data": 1,
                "subData": {}
            },
            "form": {
                "type": "string",
                "data": "",
                "subData": {}
            },
            "palette": {
                "type": "string",
                "data": "none",
                "subData": {}
            }
        }
Worked for Zarude ^

        "nbt": {
            "ndex": {
                "type": "short",
                "data": 889,
                "subData": {}
            },
            "gender": {
                "type": "byte",
                "data": 1,
                "subData": {}
            },
            "form": {
                "type": "string",
                "data": "",
                "subData": {}
            },
            "palette": {
                "type": "string",
                "data": "none",
                "subData": {}
            }
        }
Did not work for zamazenta and others in exact same format as zarude ^

![Screenshot 2022-11-23 140853](https://user-images.githubusercontent.com/93023954/203628378-85315a09-f0ef-4340-87bc-98018d98b722.png)

**Comment by danorris709** [comment]
zamazenta doesn't have a form with blank name
